parameters:
#    ns_ace_sonata.example.class: NS\AceSonataBundle\Example

services:
#    ns_ace_sonata.example:
#        class: %ns_ace_sonata.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
